# Generated by Django 4.0.5 on 2022-07-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteka', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.CharField(choices=[('Twarda', 'Twarda'), ('Miękka', 'Miękka')], default='Miękka', max_length=30, verbose_name='Okładka'),
        ),
        migrations.AlterField(
            model_name='book',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Usunąć? '),
        ),
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.FileField(blank=True, upload_to='images', verbose_name='Zdjęcie'),
        ),
    ]
